title: osome.work
description: A digital workshop created by BitCook.
url: https://osome.work
lang: zh-CN
timezone: Asia/Shanghai

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
